# Generated by Django 4.2.7 on 2024-02-01 07:30

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', clickhouse_backend.models.StringField(default='')),
                ('name', clickhouse_backend.models.StringField(default='')),
                ('mpName', clickhouse_backend.models.StringField(default='')),
                ('sellerID', clickhouse_backend.models.StringField(default='')),
                ('sellerName', clickhouse_backend.models.StringField(default='')),
                ('catID', clickhouse_backend.models.StringField(default='')),
                ('brandID', clickhouse_backend.models.StringField(default='')),
                ('brandName', clickhouse_backend.models.StringField(default='')),
                ('article', clickhouse_backend.models.StringField(default='')),
                ('mainPhoto', clickhouse_backend.models.StringField(default='')),
                ('price', clickhouse_backend.models.StringField(default='')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_overwrite_base_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
