# Generated by Django 4.2.7 on 2024-02-01 07:51

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandId', clickhouse_backend.models.StringField(default='')),
                ('name', clickhouse_backend.models.StringField(default='')),
                ('mpName', clickhouse_backend.models.StringField(default='')),
                ('url', clickhouse_backend.models.StringField(default='')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_overwrite_base_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SellerCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', clickhouse_backend.models.StringField(default='')),
                ('mpName', clickhouse_backend.models.StringField(default='')),
                ('sellerID', clickhouse_backend.models.StringField(default='')),
                ('psrn', clickhouse_backend.models.StringField(default='')),
                ('url', clickhouse_backend.models.StringField(default='')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_overwrite_base_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
